/**
 * Regenerate `src/ui/iconPaths.generated.ts` from the pinned `pixelarticons`
 * package (MIT), so the vendored icon paths are sourced from the dependency
 * rather than hand-transcribed. Run after `npm install` or a package bump:
 *
 *   node scripts/gen-icon-paths.ts
 *
 * Only the icons that have a pixelarticons equivalent live here. The custom
 * hand-drawn glyphs (mute, bomb, bulldoze, warning, pause, speed1..3, help)
 * stay in `src/ui/icons.ts`. The paths are inlined into the bundle at build
 * time, so nothing is fetched at runtime (the offline PWA and the packaged
 * shells stay self-contained). `src/ui/iconPaths.generated.test.ts` checks the
 * committed output still matches the installed package.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SVG_DIR = resolve(ROOT, "node_modules/pixelarticons/svg");

/** Project icon name -> pixelarticons SVG file (without extension). */
export const ICON_SOURCES: Record<string, string> = {
  brand: "building",
  save: "save",
  sound: "volume-2",
  stats: "chart",
  map: "map-pin",
  settings: "settings-2",
  inspect: "search",
  milestone: "flag",
  trophy: "trophy",
  fire: "fire",
  rescue: "truck",
  car: "car",
  money: "money",
  security: "shield",
  housekeeping: "trash",
  cockroach: "bug",
  santa: "gift",
  garbage: "reload",
  undo: "undo",
  redo: "redo",
  menu: "menu",
  update: "reload",
  install: "download",
  back: "chevron-left",
  play: "play",
  folder: "folder",
  plus: "plus",
};

/** The `d` attribute of every `<path>` in a pixelarticons SVG, in file order. */
export function pathsFor(file: string, svgDir: string = SVG_DIR): string[] {
  const svg = readFileSync(resolve(svgDir, `${file}.svg`), "utf8");
  const ds = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);
  if (ds.length === 0) throw new Error(`no <path d> found in ${file}.svg`);
  return ds;
}

function main(): void {
  const version = JSON.parse(
    readFileSync(resolve(ROOT, "node_modules/pixelarticons/package.json"), "utf8"),
  ).version as string;

  const entries = Object.entries(ICON_SOURCES).map(
    ([name, file]) => [name, pathsFor(file)] as const,
  );

  const sources = Object.entries(ICON_SOURCES)
    .map(([name, file]) => `  ${name}: ${JSON.stringify(file)},`)
    .join("\n");
  const paths = entries
    .map(([name, ds]) => `  ${name}: [${ds.map((d) => JSON.stringify(d)).join(", ")}],`)
    .join("\n");

  const out =
    `// AUTO-GENERATED by scripts/gen-icon-paths.ts from pixelarticons@${version}\n` +
    `// (MIT, https://github.com/halfmage/pixelarticons). Do not edit by hand; re-run\n` +
    `// the script to refresh. Custom hand-drawn glyphs live in icons.ts, not here.\n\n` +
    `/** Project icon name -> the pixelarticons file its path data came from. */\n` +
    `export const VENDORED_ICON_SOURCES: Record<string, string> = {\n${sources}\n};\n\n` +
    `/** Each icon's SVG path "d" data (currentColor fill lives on the <svg>). */\n` +
    `export const VENDORED_ICON_PATHS: Record<string, readonly string[]> = {\n${paths}\n};\n`;

  writeFileSync(resolve(ROOT, "src/ui/iconPaths.generated.ts"), out);
  console.log(`wrote src/ui/iconPaths.generated.ts (${entries.length} icons from pixelarticons@${version})`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
