/**
 * Verticopolis screenshot generator: the SINGLE source of truth for every image
 * under docs/screenshots/ (showcase), docs/screenshots/features/ (feature shots),
 * and docs/screenshots/milestones/ (the star ladder). Replaces the old fleet of
 * shot-*.mjs scripts.
 *
 * This file is the RUNNER + entry point. The rest of the generator is split by
 * execution context so each part reads on its own:
 *   • screenshot-env.ts      : output dirs, browser/server config, Shot/Scene types
 *   • screenshot-builders.ts : the page-context builders (⚠ serialized into the
 *                              browser; self-contained, see that file's banner)
 *   • screenshot-scenes.ts   : the declarative SCENES manifest (what shots exist)
 *
 * Run:  npm run screenshots        (local host capture: build + serve + shoot
 *                                    with the host Chromium. Fast, for PREVIEW
 *                                    and iteration only. Its DOM-chrome pixels
 *                                    can differ by a hair, so do NOT commit its
 *                                    output as the final set.)
 *   or: node scripts/screenshots.ts   (against an already-built dist on :4173)
 *
 * The CANONICAL committed images come from CI, never a local run: this generator
 * runs inside the pinned Playwright Docker image (one Chromium build + fonts, so
 * antialiasing is stable) and the pixels are committed back. The docs gallery is
 * regenerated by pr-drift-check.yml: it renders on every render-affecting PR and,
 * on maintainer approval of its commit-on-approval job, commits the refreshed
 * gallery to the PR branch. The e2e visual baselines are minted by
 * update-visual-baselines.yml (a `[update-baselines]` marker push). Regenerate the
 * committed set those ways, not by committing a host run.
 *
 * Determinism: once a page is ready the runner swaps the live Excalibur clock
 * for a manually stepped TestClock (pgAdoptTestClock) and every settle advances
 * whole frames (pgStep via settle()), so each capture is a pure function of the
 * seeded sim plus the step count; wall time never leaks into the pixels. DOM
 * chrome is captured with CSS animations disabled. Rerunning the generator in
 * the same pinned image therefore reproduces every PNG byte-for-byte, and a
 * regen diff means the UI actually changed.
 *
 * Env knobs: RUN_SERVER=1 spawns its own `vite preview`; ONLY=milestones,tablet
 * re-shoots just those scene ids; BASE_URL / PORT / PW_CHROME override targets;
 * SHOTS_DIR relocates the output gallery (used by the determinism guard to render
 * two independent legs into separate roots concurrently).
 *
 * TypeScript runs natively on Node ≥ 22.18 (type-stripping): no build step, no
 * extra dep. Keep every module here ERASABLE (type annotations / interfaces /
 * `as` only; no enums, namespaces, or parameter properties), and import sibling
 * modules with an explicit `.ts` extension so the native loader resolves them.
 */
import { chromium, type Browser, type Page } from "playwright";
import { spawn, type ChildProcess } from "node:child_process";
import { join } from "node:path";
import { DIRS, DESKTOP, PHONE, EXECUTABLE, PORT, BASE, assertReady, type OutDir, type Scene, type Shot } from "./screenshot-env.ts";
import { pgAdoptTestClock, pgClearTransients, pgDismissSplash, pgFrame, pgMaskVersion, pgRefreshUi, pgSetClock, pgSetOverlay, pgStep, pgStepNoDraw } from "./screenshot-builders.ts";
import { SCENES } from "./screenshot-scenes.ts";

// ---- Runner -----------------------------------------------------------------

const FRAME_MS = 1000 / 60;

// Wall-clock ceiling for a page to signal it finished booting (a route's ready
// flag, or the game object). This is only a ceiling before the scene is declared
// failed: the waits resolve the instant the page is ready, so a generous value
// costs nothing on the happy path. Sized with headroom because the determinism
// guard (screenshot-capture.yml) now renders its two legs CONCURRENTLY: the
// doubled CPU contention on the runner can slow a heavy scene's boot, and a ceiling
// tuned for one-leg-at-a-time load would flag that transient slowness as a failure.
const READY_TIMEOUT_MS = 30_000;

/** Deterministic settle: advance the page by `ms` of VIRTUAL time by stepping
 *  the adopted TestClock in whole frames, so identical runs replay identical
 *  frames (the sim feed, elevator/crowd motion, and the decorative animation
 *  clock all advance per step, never per wall-clock). Rounds UP so a positive
 *  `ms` always covers at least that much virtual time (never under-steps and
 *  captures a hair early); `ms <= 0` steps nothing, honoring the contract
 *  exactly. Pages with no engine clock fall back to a real wait: the route
 *  pages (gallery/preview) are frozen by the pinned performance.now set in
 *  runScene, and the composite setContent shots are static markup, so a wall
 *  wait can't shift either. */
async function settle(page: Page, ms: number, drawEveryFrame = false): Promise<void> {
  // ceil already yields >= 1 frame for any ms > 0, so no lower clamp is needed;
  // ms <= 0 yields <= 0, which the stepper treats as "no step" (returns false).
  // Default: skip the intermediate draws (pgStepNoDraw). A settle always draws its
  // FINAL frame either way; the flag only decides whether the discarded frames
  // BEFORE it also draw. Skipping them is wasted software raster, and pgStepNoDraw's
  // drawPos sync keeps the final frame byte-identical, so it is safe gallery-wide
  // EXCEPT a few draw-coupled shots (per-shot viewport resizes, draw-path animation):
  // those pass drawEveryFrame=true (via the shot's drawSettle). Route scene-level
  // settles also draw every frame (see runScene): a live-engine route page is
  // draw-sensitive.
  const step = drawEveryFrame ? pgStep : pgStepNoDraw;
  const stepped = await page.evaluate(step, Math.ceil(ms / FRAME_MS));
  if (!stepped) await page.waitForTimeout(Math.max(0, ms));
}

let captured = 0;
const failures: string[] = [];
const perDir: Record<OutDir, number> = { screenshots: 0, features: 0, milestones: 0 };
// Per-scene wall time, appended as each scene finishes, for the closing "slowest
// scenes" summary. stdout only: never read back into the page and never written
// into a PNG, so it cannot move a committed pixel or affect determinism.
const sceneTimings: { id: string; ms: number }[] = [];

async function takeShot(page: Page, scene: Scene, shot: Shot): Promise<void> {
  const shotStart = Date.now();
  const outDir = shot.outDir ?? scene.outDir;
  const path = join(DIRS[outDir], `${shot.name}.png`);
  const baseVp = scene.viewport ?? DESKTOP;
  if (shot.viewport) {
    await page.setViewportSize(shot.viewport);
    // Excalibur sizes its canvas from a ResizeObserver (DisplayMode.FillContainer),
    // whose callback fires on the browser's own schedule, NOT the stepped clock.
    // If we start stepping before it runs, the resize (canvas dims + camera) lands
    // at a wall-dependent moment relative to the frames and the capture, so a
    // viewport-override shot on a live engine (e.g. tablet-compact) drifts
    // run to run. Flush the observer with two rAFs first (observers deliver
    // before paint; the stopped Excalibur clock means this advances no sim or
    // animation time) so the new size is fully applied before the settle steps.
    await page.evaluate(
      () => new Promise<void>((r) => requestAnimationFrame(() => requestAnimationFrame(() => r()))),
    );
  }
  try {
    if (shot.clock !== undefined) await page.evaluate(pgSetClock, shot.clock);
    // Always drive the overlay dropdown (default "") so a prior shot's overlay
    // never bleeds into the next, so every shot gets a clean map state.
    await page.evaluate(pgSetOverlay, shot.overlay ?? "");
    if (shot.setup) await shot.setup(page);
    if (shot.frame) {
      await page.evaluate(pgFrame, { tile: shot.frame.tile ?? null, floor: shot.frame.floor, zoom: shot.frame.zoom });
    }
    await settle(page, shot.wait ?? 500, shot.drawSettle ?? false);
    // Repaint the throttled DOM chrome off the final sim state, then sweep
    // stray toasts / event dialogs the running sim may have popped during the
    // settle, unless this shot is deliberately showing a modal.
    await page.evaluate(pgRefreshUi);
    const keepDialogs = shot.keepDialogs ?? (!!shot.crop && shot.crop.includes("modal"));
    await page.evaluate(pgClearTransients, keepDialogs);
    // Mask the app version to a fixed placeholder so a routine version bump does
    // not churn the splash/help pixels (the shipped app still shows the real one).
    await page.evaluate(pgMaskVersion);
    await page.waitForTimeout(80);
    // animations: "disabled" freezes CSS animation (the splash star twinkle,
    // the onboarding pulse) at a fixed phase so DOM chrome is byte-stable too.
    if (shot.crop) {
      await page.locator(shot.crop).screenshot({ path, animations: "disabled" });
    } else {
      await page.screenshot({ path, fullPage: !!shot.fullPage, animations: "disabled" });
    }
  } finally {
    // Always restore the scene viewport, even if the shot threw, so one failed
    // shot can't cascade a wrong size into the rest of the scene.
    if (shot.viewport) await page.setViewportSize(baseVp);
  }
  captured++;
  perDir[outDir]++;
  console.log(`  ✓ ${outDir}/${shot.name} (${Date.now() - shotStart} ms)`);
}

async function runScene(browser: Browser, scene: Scene): Promise<void> {
  const sceneStart = Date.now();
  console.log(`\n▶ scene: ${scene.id}`);
  const vp = scene.viewport ?? DESKTOP;
  // A phone-sized scene must also present as a touch device, or `@media (pointer:
  // coarse)` / mobile-only chrome never applies and the "mobile" shot renders the
  // desktop UI. isMobile/hasTouch are Chromium-only (we always launch Chromium).
  const mobile = vp.width <= PHONE.width;
  const page = await browser.newPage({ viewport: vp, deviceScaleFactor: scene.outDir === "screenshots" ? 1 : 2, isMobile: mobile, hasTouch: mobile });
  page.on("pageerror", (e) => console.error("  PAGE ERROR:", e.message));
  try {
    if (scene.route) {
      // Route pages (e.g. preview.html) animate off performance.now(); pin it to a
      // constant BEFORE any page script runs so the captured frame is byte-stable
      // even inside the pinned container. Each route page sets its ready flag
      // synchronously at module load, so freezing the timer never blocks it.
      await page.addInitScript(() => {
        const t = 1_000;
        // Assigning performance.now directly can throw in a hardened Chromium
        // (the property may be non-writable); define it defensively and never
        // let this break navigation.
        try {
          Object.defineProperty(performance, "now", { configurable: true, value: () => t });
        } catch {
          try {
            performance.now = () => t;
          } catch {
            /* keep the real clock; the frame just won't be perfectly frozen */
          }
        }
      });
    }
    if (scene.initScript) await page.addInitScript(scene.initScript);
    await page.goto(scene.route ? `${BASE}/${scene.route}` : BASE, { waitUntil: "networkidle" });
    if (scene.route) {
      // Route pages set their own ready flag (galleryReady / previewReady).
      // A missing flag means the page never finished rendering, so capturing now would
      // commit a blank/half-drawn PNG over a good one. Record the failure and SKIP the
      // scene's shots entirely, leaving the existing committed images untouched.
      try {
        await page.waitForFunction(() => {
          const w = window as any;
          return w.galleryReady === true || w.previewReady === true;
        }, null, { timeout: READY_TIMEOUT_MS });
      } catch {
        for (const shot of scene.shots) {
          failures.push(`${scene.id}/${shot.name}: route never signaled ready, skipped (no new image written)`);
          console.error(`  ✗ ${shot.name}: route never ready, skipped`);
        }
        return;
      }
      // The route pages (gallery/preview) have no engine, so "none" is expected
      // here: they are already frozen by the pinned performance.now above. The
      // guard stays defensive: if a route page ever did carry an engine whose
      // clock could not be swapped, that must fail the scene rather than silently
      // capture wall-clock pixels.
      if ((await page.evaluate(pgAdoptTestClock)) === "failed") {
        throw new Error("engine present but test-clock adoption failed");
      }
      // The route pages (gallery/preview) have no engine clock, so this settle
      // wall-waits regardless of the draw flag; passing true is harmless and
      // keeps one code path for route settles.
      await settle(page, 800, true);
    } else {
      await page.waitForFunction(() => !!(window as any).game, null, { timeout: READY_TIMEOUT_MS });
      // From here on, frames advance only when settle()/pgStep drives them:
      // wall time (rAF jitter, CI load, staging latency) can no longer leak
      // into what the sim and the decorations look like at capture. A failed
      // adoption would silently revert the page to wall-clock timing, so it
      // fails the scene (existing committed images stay untouched).
      if ((await page.evaluate(pgAdoptTestClock)) !== "adopted") {
        throw new Error("test-clock adoption failed on the game page");
      }
      if (!scene.keepSplash) await page.evaluate(pgDismissSplash);
      if (scene.build) await page.evaluate(scene.build);
      if (scene.assertUnits) await assertReady(page, scene.assertUnits);
    }
    for (const shot of scene.shots) {
      try {
        await takeShot(page, scene, shot);
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        failures.push(`${scene.id}/${shot.name}: ${msg}`);
        console.error(`  ✗ ${shot.name}: ${msg}`);
      }
    }
  } finally {
    // page.close() is cleanup: never let it throw past the finally (that would fail
    // a scene whose shots all captured) and never let it skip the timing row. Log a
    // close failure and carry on; the browser is torn down in main's finally anyway.
    try {
      await page.close();
    } catch (e) {
      console.error(`  page.close failed for scene ${scene.id}: ${e instanceof Error ? e.message : String(e)}`);
    }
    const sceneMs = Date.now() - sceneStart;
    sceneTimings.push({ id: scene.id, ms: sceneMs });
    // The route-not-ready early return above also passes through this finally, so a
    // scene that failed to render still gets a timing row. That row reflects the
    // wall time actually spent, which for a route that never signaled ready is the
    // readiness wait (up to READY_TIMEOUT_MS), not zero; either way it is a useful
    // signal that the scene did not capture normally.
    console.log(`◀ scene: ${scene.id} (${(sceneMs / 1000).toFixed(1)}s)`);
  }
}


// ---- main -------------------------------------------------------------------

async function main(): Promise<void> {
  let server: ChildProcess | null = null;
  if (process.env.RUN_SERVER) {
    server = spawn("npx", ["vite", "preview", "--port", String(PORT)], { stdio: "inherit" });
    // Wait for the preview server to answer.
    const ok = await (async () => {
      for (let i = 0; i < 40; i++) {
        try {
          const res = await fetch(BASE);
          if (res.ok) return true;
        } catch {
          /* not up yet */
        }
        await new Promise((r) => setTimeout(r, 500));
      }
      return false;
    })();
    if (!ok) {
      server.kill("SIGTERM");
      throw new Error("vite preview did not come up");
    }
  }

  // ONLY=scene-id[,scene-id] re-shoots a subset (fast iteration); default all.
  const only = (process.env.ONLY || "").split(",").map((s) => s.trim()).filter(Boolean);
  const scenes = only.length ? SCENES.filter((sc) => only.includes(sc.id)) : SCENES;
  // Launch INSIDE the try so a launch failure still runs the finally that kills
  // the spawned vite preview (otherwise it orphans on :4173 and the next run
  // captures against a stale build).
  let browser: Browser | undefined;
  try {
    browser = await chromium.launch({ executablePath: EXECUTABLE });
    for (const scene of scenes) {
      // A scene's setup (game wait / build / assertReady) can throw; keep it from
      // aborting the whole run. Record every shot in the scene as failed (so its
      // existing committed image is left untouched) and move to the next scene.
      try {
        await runScene(browser, scene);
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        for (const shot of scene.shots) failures.push(`${scene.id}/${shot.name}: scene setup failed (${msg})`);
        console.error(`  ✗ scene ${scene.id} aborted: ${msg}`);
      }
    }
  } finally {
    if (browser) await browser.close();
    if (server) server.kill("SIGTERM");
  }

  console.log(`\n──────── captured ${captured} shots ────────`);
  for (const d of Object.keys(perDir) as OutDir[]) console.log(`  ${d.padEnd(12)} ${perDir[d]}`);
  // Slowest scenes first, so a CI log makes the render long poles obvious at a
  // glance (this is what tells us where a shard's time actually goes).
  const totalMs = sceneTimings.reduce((sum, s) => sum + s.ms, 0);
  const slowest = [...sceneTimings].sort((a, b) => b.ms - a.ms);
  console.log(`\n──────── slowest scenes (total ${(totalMs / 1000).toFixed(1)}s) ────────`);
  for (const s of slowest) console.log(`  ${s.id.padEnd(20)} ${(s.ms / 1000).toFixed(1)}s`);
  if (failures.length) {
    console.log(`\n${failures.length} FAILURE(S):`);
    for (const f of failures) console.log(`  ✗ ${f}`);
    process.exitCode = 1;
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
